
# ------------------------------------------------------------------------
# Copyright (c) 2020-2023 Riccardo De Martis. MIT License.
# All Trademarks referred to are the property of their respective owners.
# ------------------------------------------------------------------------

# This is the master workflow, taken by CI of GitHub.
# It (only) aims at properly organizing the sub-workflows.

name: CI

on:
  push:
    branches:
      - "main"

concurrency:
  group: CI-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Create cache folders
#        run: mkdir /tmp/.buildx-cache /tmp/.buildx-cache-new

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ${{ env.DOCKERHUB_REPO }}

      -
        name: Build and push test
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: dummy:latest

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache (Temp fix)
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      -
        name: Image simple test
        run: |
          echo ${{ github.workspace }}
          ls ${{ github.workspace }}
          ls ${{ github.workspace }}/test

#      -
#        name: Image simple test
#        run: |
#          docker run --rm dummy:latest ls ${{ github.workspace }}


      - name: Image simple test
        run: |
          docker run -v `pwd`/test:/test --rm dummy:latest  bash -c "chmod +x /test/mcr_version.sh && /test/mcr_version.sh PRova"
#      -
#        name: Image MCR version check Test
#        run: |
#          ls && docker run -v `pwd`/../test:/test --rm dummy:latest bash /test/mcr_version.sh Arara
#
#      -
#        name: Build and push (cached) :${{ inputs.DOCKERHUB_TAG }} ${{ inputs.is_latest == true && 'and :latest' || '' }} ${{ inputs.is_latest_meshlab == true && 'and :latest-meshlab' || '' }}
#        uses: docker/build-push-action@v5
#        with:
#          context: ./${{ inputs.DOCKER_CONTEXT }}
#          push: true
#          platforms: linux/amd64
#          cache-from: type=local,src=/tmp/.buildx-cache
##          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
#          tags: |
#            ${{ inputs.DOCKERHUB_REPO }}:${{ inputs.DOCKERHUB_TAG }}
#            ${{ inputs.is_latest == true && format('{0}:latest', inputs.DOCKERHUB_REPO) || '' }}
#            ${{ inputs.is_latest_meshlab == true && format('{0}:latest-meshlab', inputs.DOCKERHUB_REPO) || '' }}
#
##      - # Temp fix
##        # https://github.com/docker/build-push-action/issues/252
##        # https://github.com/moby/buildkit/issues/1896
##        name: Move cache (Temp fix)
##        run: |
##          rm -rf /tmp/.buildx-cache
##          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
#
#      -
#        name: MCR version check
#        run: |
#          docker run -v `pwd`/../test:/test --rm ${{ inputs.DOCKERHUB_REPO }}:${{ env.TEST_TAG }} bash /test/mcr_version.sh ${{ inputs.DOCKERHUB_TAG }}
#      -
#        name: MCR Test (Temp skipped)
#        continue-on-error: true
#        run: |
#          docker run --rm ${{ inputs.DOCKERHUB_REPO }}:${{ inputs.DOCKERHUB_TAG }} echo "TODO: ADD MCR TEST"
#
